---
title: "NMDS"
format: html
editor: visual
---

# Packages

```{r}
library(vegan)
library(tidyverse)
library(ggplot2)
library(ggvegan)
library(ggpubr)
library(analogue)
```

#### NMDS analysis

-   I changed the ctd plots to follow depth distribution
-   the NMDS plots are for mean of each environmental variable (salinity, temperature, and oxygen)

```{r}
nmds_density<- function(mydf, event)
{ mydf |> 
  filter(sampling_event %in% event) |>
  mutate(
    net_area_m2 = as.numeric(net_area_m2),
    sampling_depth = as.numeric(sampling_depth)
    ) |> 
  mutate(
    filtered_seawater = net_area_m2 * sampling_depth,
    chromista_sp_indet_p_elegans = as.numeric(chromista_sp_indet_p_elegans)/filtered_seawater,
    hysterothylacium_aduncum = as.numeric(hysterothylacium_aduncum)/filtered_seawater,
    gregarinasina_sp_indet = as.numeric(gregarinasina_sp_indet)/filtered_seawater,
    ciliophora_sp_indet = as.numeric(ciliophora_sp_indet)/filtered_seawater,
    didymozoid_sp_indet = as.numeric(didymozoid_sp_indet)/filtered_seawater,
    diphyllobothrium_sp = as.numeric(diphyllobothrium_sp)/filtered_seawater,
    station = factor(station) ) |> 
  mutate(
    filtered_seawater = round(filtered_seawater, digits = 1),
    chromista_sp_indet_p_elegans = round(chromista_sp_indet_p_elegans * 100, digits = 1),
    hysterothylacium_aduncum = round(hysterothylacium_aduncum * 100, digits = 1),
    gregarinasina_sp_indet = round(gregarinasina_sp_indet * 100, digits = 1),
    ciliophora_sp_indet = round(ciliophora_sp_indet * 100, digits = 1),
    didymozoid_sp_indet = round(didymozoid_sp_indet * 100, digits = 1),
    diphyllobothrium_sp = round(diphyllobothrium_sp * 100, digits = 1)
  )|> 
   pivot_longer(cols = c(hysterothylacium_aduncum, gregarinasina_sp_indet, ciliophora_sp_indet, didymozoid_sp_indet, chromista_sp_indet_p_elegans, diphyllobothrium_sp),
               names_to = "parasite_species",
               values_to = "density"
               ) |> 
  mutate(parasite_species = case_when(
                        str_detect(parasite_species, "^hysterothylacium_aduncum") ~ "Hysterothylacium aduncum",
                        str_detect(parasite_species, "^gregarinasina_sp_indet") ~ "Gregarine-like parasites",
                        str_detect(parasite_species, "^ciliophora_sp_indet") ~ "Cilates",
                        str_detect(parasite_species, "^didymozoid_sp_indet") ~ "Didymozoidae sp. indet",
                        str_detect(parasite_species, "^chromista_sp_indet_p_elegans") ~ "Chromista sp. indet",
                        str_detect(parasite_species, "^diphyllobothrium_sp") ~ "Diphyllobothrium sp.",
                        TRUE ~ parasite_species)) |> 
    mutate(
      sampling_date = parse_date(sampling_date, format = "%B %Y"),
      month = factor(format(sampling_date, "%b"),
                    levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun",
                             "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"),
                    ordered = TRUE),
      year = factor(format(sampling_date, "%Y"),
                    levels = c("2023", "2024"),
                    ordered = TRUE)
      ) |> 
    mutate(parasites_species = factor(parasite_species,
                     levels=c( "Gregarine-like parasites", "Hysterothylacium aduncum", "Cilates", "Didymozoidae sp. indet", "Diphyllobothrium sp.", "Chromista sp. indet"),
                     ordered =TRUE)) |> 
    replace_na(list(density = 0)) |> 
    select(parasite_species, density, year, month, sampling)
  
}

nmds_density4<- nmds_density(mydf = dynamics, event = "4")
nmds_density4  


```

```{r}
nmds_ctd <- combined_24_mean |> # combined_mean from CTD data file 
  rename(station = "location", sampling = "sampling_trip") |>
 mutate(month = case_when(
                        str_detect(month, "January") ~ "Jan",
                        str_detect(month, "February") ~ "Feb",
                        str_detect(month, "March") ~ "Mar",
                        str_detect(month, "April") ~ "Apr",
                        str_detect(month, "May") ~ "May",
                        str_detect(month, "June") ~ "Jun",
                        str_detect(month, "July") ~ "Jul",
                        str_detect(month, "August") ~ "Aug",
                        str_detect(month, "September") ~ "Sep",
                        str_detect(month, "October") ~ "Oct",
                        str_detect(month, "November") ~ "Nov",
                        str_detect(month, "December") ~ "Dec",
                        TRUE ~ month)) |> 
  mutate(mean_salinity = as.numeric(mean_salinity, na.rm = TRUE),
         mean_oxygen = as.numeric(mean_oxygen, na.rm = TRUE),
         mean_temperature = as.numeric(mean_temperature, na.rm = TRUE)) |> 
  select(mean_temperature, station, year, month, mean_salinity, mean_oxygen)
nmds_ctd
```

```{r}
# Joining the ctd data and density data
nmds_matrix <- left_join(nmds_density4, nmds_ctd)

# transform to right matrix format
matrix <- nmds_matrix |> 
  filter(station != "Fanafjord") |> 
 # select(parasite_species, density, sampling) |> 
  #arrange(by = month, station) |> 
  #group_by(month, station) |> 
pivot_wider(names_from = parasite_species, values_from = density, values_fill = 0, values_fn = sum) |> 
  drop_na() |> 
  rename(Hys = "Hysterothylacium aduncum", Greg = "Gregarine-like parasites", Cil = "Cilates", Did =  "Didymozoidae sp. indet", Chro = "Chromista sp. indet", Diph = "Diphyllobothrium sp.", temp = "mean_temperature", oxy = "mean_oxygen", sal = "mean_salinity")

# |> 
#  select("Hysterothylacium aduncum","Gregarine-like parasites", "Cilates","Didymozoidae sp. indet", "Chromista sp. indet",
     #    "Diphyllobothrium sp.")
 
# Species matrix
species_matrix<- matrix |> 
  select("Hys","Greg", "Cil","Did", "Chro",
         "Diph")# |> 
  #filter(!row_number() %in% c(30))
#|> 
  #as.matrix()
  
# Environmental data
env_data <- matrix |> 
  select(month, year, station, temp, sal, oxy)
 


```

```{r}
density_total_vct <- rowSums(species_matrix)

density_total <- species_matrix |> 
  mutate(density = density_total_vct)

mva_species_tf <- species_matrix |> 
    tran(method = "rootroot")
```

```{r}

# Perform NMDS analysis
set.seed(123)  # For reproducibility
nmds <- metaMDS(mva_species_tf,  # mva_species_tf
                distance = "bray",  # Bray-Curtis dissimilarity
                k = 2,             # 3 dimensions as specified
                trymax = 20)       # 20 runs for stability

# Check stress values
stressplot(nmds)

# Create environmental data frame


# Run envfit analysis
env_fit <- envfit(nmds, env_data, 
                  permutations = 999)

dim(nmds)  # Should show number of samples and 2 columns (NMDS1, NMDS2)
dim(env_data)

vector_coords <- as.data.frame(scores(env_fit, "vectors"))
vector_coords$variable <- rownames(vector_coords)

# scale arrows
arrow_multiplier <- 1.5
vector_coords <- transform(vector_coords,
                              NMDS1 = NMDS1 * arrow_multiplier,
                            NMDS2 = NMDS2 * arrow_multiplier)

# Calculate species correlations with ordination axes
species_envfit <- envfit(nmds, mva_species_tf,
                        permutations = 999)

# Get species coordinates
species_coords <- as.data.frame(scores(species_envfit, "vectors"))
species_coords$variable <- rownames(species_coords)

# Scale the arrows
arrow_multiplier <- 1.5
species_coords <- transform(species_coords,
                          NMDS1 = NMDS1 * arrow_multiplier,
                          NMDS2 = NMDS2 * arrow_multiplier)

# Categorical envfit scores (location, month, year)

factor_coords <- as.data.frame(scores(env_fit, "factors"))
factor_coords$variable <- rownames(factor_coords)

nmds_df <- as.data.frame(scores(nmds))
cool <- cbind(env_data, nmds_df)




```
#### NMDS plot

```{r}

cool$month <- factor(cool$month, levels = c("Jan", "Feb", "Mar", "Apr", 
                                           "May", "Jun", "Jul", "Aug", 
                                           "Sep", "Oct", "Nov", "Dec"))
# Add vectors to the plot
nmds_plot4<- ggplot(cool, aes(x = sites.NMDS1, y = sites.NMDS2)) +
geom_point(aes(color = year, shape = year), size = 4, alpha = 0.7, stroke = 0.5) +

  #geom_label_repel(aes(label = month)) +
  geom_text(aes(label = month, colour = year), 
           hjust = -0.4,     # Horizontal adjustment (0 = left-aligned)
           vjust = 0,
           size = 3) +
 # geom_abline(intercept = 0, slope = 0, linetype = "dashed") +
  #geom_vline(aes(intercept = 0), linetype = "dashed") +
  geom_segment(data = vector_coords,
              aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2),
              arrow = arrow(length = unit(0.3, "cm")),
              color = "blue",
              size = 0.8, 
              alpha = 0.5) +
  geom_text(data = vector_coords,
            aes(x = NMDS1, y = NMDS2, label = variable),
            vjust = -0.5, 
            color = "blue") +
  geom_segment(data = species_coords,
              aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2),
              arrow = arrow(length = unit(0.3, "cm")),
              size = 0.8,
              alpha = 0.5,
              color = "cyan4",
              alpha = 0.5) +
  geom_text(data = species_coords,
            aes(x = NMDS1, y = NMDS2, label = variable),
            vjust = -0.5) +
 scale_color_manual(values = c("deeppink4", "lightpink3")) +
    theme_minimal() +
  coord_fixed() +
  labs(x = "NMDS1", y = "NMDS2")+
  annotate("label", x = -0.4, y = -1,
           label = "Stress: 0.06",
           color = "black",
           size = 3)
nmds_plot4

```

stress values is: 0.0306413, stress type 1, weak ties

```{r}
ggsave(here("output", "nmds_plot4.png"), plot = nmds_plot4, width = 170, height = 160, units = "mm", scale = 1.2)

```




